executors:
  # the Docker image with Cypress dependencies and Chrome browser
  cy-doc:
    docker:
      - image: cypress/browsers:node16.16.0-chrome106-ff99-edge
    # by default, we use "medium" to balance performance + CI costs. bump or reduce on a per-job basis if needed.
    resource_class: medium
    environment:
      PLATFORM: linux
      CI_DOCKER: "true"

  # Docker image with non-root "node" user
  non-root-docker-user:
    docker:
      - image: cypress/browsers:node16.16.0-chrome106-ff99-edge
        user: node
    environment:
      PLATFORM: linux

  # executor to run on Mac OS
  # https://circleci.com/docs/2.0/executor-types/#using-macos
  # https://circleci.com/docs/2.0/testing-ios/#supported-xcode-versions
  mac:
    macos:
      # Executor should have Node >= required version
      xcode: "14.0.0"
    resource_class: macos.x86.medium.gen2
    environment:
      PLATFORM: darwin

  # executor to run on Windows - based off of the windows-orb default executor since it is
  # not customizable enough to align with our existing setup.
  # https://github.com/CircleCI-Public/windows-orb/blob/master/src/executors/default.yml
  # https://circleci.com/docs/2.0/hello-world-windows/#software-pre-installed-in-the-windows-image
  windows: &windows-executor
    machine:
      image: windows-server-2019-vs2019:stable
      shell: bash.exe -eo pipefail
    resource_class: windows.large
    environment:
      PLATFORM: windows

  darwin-arm64: &darwin-arm64-executor
    machine: true
    environment:
      PLATFORM: darwin

  linux-arm64: &linux-arm64-executor
    machine:
      image: ubuntu-2004:2022.04.1
    resource_class: arm.medium
    environment:
      PLATFORM: linux
      # TODO: Disabling snapshots for now on Linux Arm 64 architectures. Will revisit with https://github.com/cypress-io/cypress/issues/23557
      DISABLE_SNAPSHOT_REQUIRE: 1
